### ISSUE TITLE
Clue Recipe in Chem Station broken

### ISSUE THREAD

**Issue by codem1966** [War3zuk/War3zuk-Alpha-18-Stable-ModLets#2]
When attempting to make clue in the chem station,  the recipe shows as 1 murky water and 0 bones.   It also only allows you to make 1 clue at a time.

The campfire recipe does work.  It requires 2 bones and 1 murky water.

**Comment by War3zuk** [comment]
Updated.. Think this is one of my old modlets so updated it with Both xmls also so its DMT compatible..

**Comment by War3zuk** [comment]
Fixed

**Comment by codem1966** [comment]
Verified.  Looks good.

BTW,  those posters are awesome too
