### ISSUE TITLE
AssetBundle conflict.

### ISSUE THREAD

**Issue by codem1966** [War3zuk/War3zuk-Alpha-18-Stable-ModLets#4]
Not sure if this is something I did wrong with the mods or not.  I simply placed them in the Mods folder in the dedicated server folder.   I can several of the following errors when loading up.  This is just an example.   If you would like,  I can post all of them.

The AssetBundle 'HDColtM1911Silencer.unity3d' can't be loaded because another AssetBundle with the same files is already loaded.
2020-03-20T18:07:59 123.069 ERR Loading AssetBundle "C:/Steam/steamapps/common/7 Days to Die Dedicated Server/7DaysToDieServer_Data/../Mods\War3zuk HD

**Comment by War3zuk** [comment]
Do you have the AIO & the HD Guns & Ammo together , if not post all mods that you have cos this isnt an error with my modlet....

**Comment by codem1966** [comment]
What is the AIO mod?   I have all the mods from this modlet repo except the ReGrow mods and the Extra Deco mod

**Comment by codem1966** [comment]
Mis-understood.  yes.  I'm using everything from AIO except the regrow stuff.   I pull your repo down and then copy the appropriate folders to the 7dtd Mods folder.
