### ISSUE TITLE
ERR XML loader

### ISSUE THREAD

**Issue by GameplaysDavis** [War3zuk/War3zuk-Alpha-18-Stable-ModLets#5]
Hello, I wanted to warn you that I found the following error, according to here it is a problem of an xml loading error and it says;

ArgumentException: An item with the same key has already been added. Key: ParticleEffects / p_snowtorm1

It is the error that the console of my server throws at me, I warn you in case you did not know why I saw that you were adding and modifying some mods, the truth is that your mods are fantastic and I would like to tell you that my server is in version 18.4, I wanted to know if once you go to alpha 19, there is a possibility that you will continue to make mods for version 18.4, it happens that I would not like to destroy the camp that we have with so much effort and time that we dedicate in building and the truth is 200 days and it is not worth it It is worth doing everything again, so it would be good if you made mod-style content from alpha 19 to 18.4, greetings and thanks from Argentina

**Comment by War3zuk** [comment]
That error speaks for itself, Its a dupe meaning your running another mod
thats conflicting with mine.. so not a mod error... & yeah the mod will
always work for alpha 18.4 as 19 will mean a total change of models & files

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by GameplaysDavis** [comment]
well, thanks and if I have other mods, the topic I don't know what it is, maybe some other that I didn't see but I'm going to review well, but I would like you to add or make other packs of models such as cars, motorcycles and maybe some vehicle that I saw by the community called Mauser that it has giant wheels, that would be great with your models, the mods are great, which would be nice if an on / off can be added in the junker, well anyway I thank you for your answer and I will fix the conflict well, thanks!

**Comment by GameplaysDavis** [comment]
> bueno, gracias y si tengo otras modificaciones, el tema no sé de qué se trata, tal vez alguna otra que no vi pero que voy a revisar bien, pero me gustaría que agreguen o hagan otros paquetes de modelos como automóviles, motocicletas y tal vez algún vehículo que vi por la comunidad llamada Mauser que tiene ruedas gigantes, eso sería genial con sus modelos, los mods son geniales, lo que sería bueno si se puede agregar un encendido / apagado en el junker, bueno, de todos modos, gracias por tu respuesta y arreglaré bien el conflicto, ¡gracias!

I wanted to say Marauder no Mauser

**Comment by War3zuk** [comment]
Dont add errors if your running different mods & dont know enough to understand why its important not to that when posting issues

**Comment by codem1966** [comment]
FYI.  I get the same error when I have the Extra Deco Ore modlet in place.   Once I remove it, I don't see that error.  Since I'm using only the "War3zuk" mods at this time,  it must be conflicting with something in  the All-In-One pack.   

Regardless it doesn't appear to break the server or gameplay... so probably not worth time/effort to find the issue.    If I have more relevant information with specifics to isolate the issue better, I'll let you know.. but at this point I don't believe it's critically affecting the game.

**Comment by War3zuk** [comment]
Thats because the extra deco has a prefabs folder containing the prefabs that need to be placed into the games prefab folder so the game can load them...

**Comment by GameplaysDavis** [comment]
Hi, if you will excuse me for that comment, I just told you that because I was looking for a way to contact you privately, it is that I wanted you to make some mods for my server and I did not know how to speak to you, and if the mod download the AIO and it's perfect, so comment something else. and if you could please leave me some contact it would be ideal to talk around there obviously we would talk for a budget by paypal. At the moment on my server they are all happy with your mod it is very fantastic and beautiful. I clarify and I am a google translator because my English is bad, I tell you in case you do not understand something

**Comment by War3zuk** [comment]
Search war3zuk on Nexus.com theres my discord info in there

**Comment by GameplaysDavis** [comment]
Ok , thanksssss 😄
